CaffeineBookatableProject/Models/Jobrespons.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaffeineBookatableProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Jobrespons
    {
        public int user_id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int Job_Position { get; set; }
        public string Resume { get; set; }
        public HttpPostedFileBase Resum { get; set; }
        public int Phone { get; set; }
    
        public virtual Carrer Carrer { get; set; }
    }
}

CaffeineBookatableProject/Controllers/JobresponsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CaffeineBookatableProject.Models;

namespace CaffeineBookatableProject.Controllers
{
    public class JobresponsController : Controller
    {
        private OnlineBookingEntities db = new OnlineBookingEntities();

        // GET: Jobrespons
        public ActionResult Index()
        {
            var jobresponses = db.Jobresponses.Include(j => j.Carrer);
            return View(jobresponses.ToList());
        }

        // GET: Jobrespons/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jobrespons jobrespons = db.Jobresponses.Find(id);
            if (jobrespons == null)
            {
                return HttpNotFound();
            }
            return View(jobrespons);
        }

        // GET: Jobrespons/Create
        public ActionResult Create()
        {
            ViewBag.Job_Position = new SelectList(db.Carrers, "career_id", "carrer_designation");
            return View();
        }

        // POST: Jobrespons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Jobrespons jobrespons)
        {
            if (ModelState.IsValid)
            {

                jobrespons.Resum.SaveAs(Server.MapPath("~/Resumes/" + jobrespons.Resum.FileName));
                //product.Prod_Pic = "~/ProPic/" + product.Pro_Pic.FileName;
                if (jobrespons.Resum.FileName != "")
                {
                    jobrespons.Resume = "~/Resumes/" + jobrespons.Resum.FileName;
                    db.Jobresponses.Add(jobrespons);
                    db.SaveChanges();
                }
                else
                {
                    jobrespons.Resume = null;
                }

                return RedirectToAction("Index","Home");
            }

            ViewBag.Job_Position = new SelectList(db.Carrers, "career_id", "carrer_designation", jobrespons.Job_Position);
            return View(jobrespons);
        }

        // GET: Jobrespons/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jobrespons jobrespons = db.Jobresponses.Find(id);
            if (jobrespons == null)
            {
                return HttpNotFound();
            }
            ViewBag.Job_Position = new SelectList(db.Carrers, "career_id", "carrer_designation", jobrespons.Job_Position);
            return View(jobrespons);
        }

        // POST: Jobrespons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "user_id,Name,Email,Job_Position,Resume,Phone")] Jobrespons jobrespons)
        {
            if (ModelState.IsValid)
            {
                db.Entry(jobrespons).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Job_Position = new SelectList(db.Carrers, "career_id", "carrer_designation", jobrespons.Job_Position);
            return View(jobrespons);
        }

        // GET: Jobrespons/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jobrespons jobrespons = db.Jobresponses.Find(id);
            if (jobrespons == null)
            {
                return HttpNotFound();
            }
            return View(jobrespons);
        }

        // POST: Jobrespons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Jobrespons jobrespons = db.Jobresponses.Find(id);
            db.Jobresponses.Remove(jobrespons);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CaffeineBookatableProject/Views/Jobrespons/Create.cshtml
@model CaffeineBookatableProject.Models.Jobrespons

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<!DOCTYPE html>
<html>
<head>
    <title>Job Application Form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

    <div class="container">
        @using (Html.BeginForm("Create", "Jobrespons", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            <h4>Job Application</h4>
            <hr />

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group row">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-md-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "col-md-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Job_Position, "Job_Position", htmlAttributes: new { @class = "col-md-2 col-form-label" })
                <div class="col-md-10">
                    @Html.DropDownList("Job_Position", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Job_Position, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Resume, htmlAttributes: new { @class = "col-md-2 col-form-label" })
                <div class="col-md-10">
                    <input type="file" name="Resume" class="form-control-file">
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "col-md-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                <div class="offset-md-2 col-md-10">
                    <input type="submit" value="Confirm" class="btn btn-primary" />
                </div>
            </div>
        }
    </div>

</body>
</html>

CaffeineBookatableProject/Views/Jobrespons/Delete.cshtml
@model CaffeineBookatableProject.Models.Jobrespons

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Jobrespons</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Resume)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Resume)
        </dd>

        <dt>
            <a href="@Url.Content(Model.Resume)" class="btn btn-outline-success">Download</a>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Carrer.carrer_designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Carrer.carrer_designation)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CaffeineBookatableProject/Views/Jobrespons/Details.cshtml
@model CaffeineBookatableProject.Models.Jobrespons

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}


<!DOCTYPE html>
<html>
<head>
    <title>Job Details</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div class="card-header">
                        <h4>Job Responsibilities</h4>
                    </div>
                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.Name)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.Name)
                            </dd>

                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.Email)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.Email)
                            </dd>

                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.Resume)
                            </dt>
                            <dd class="col-sm-8">
                                <a href="@Url.Content(Model.Resume)" class="btn btn-success">Download Resume</a>
                            </dd>

                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.Phone)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.Phone)
                            </dd>

                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.Carrer.carrer_designation)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.Carrer.carrer_designation)
                            </dd>
                        </dl>
                    </div>
                    <div class="card-footer">
                        @Html.ActionLink("Edit", "Edit", new { id = Model.user_id }, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

CaffeineBookatableProject/Views/Jobrespons/Edit.cshtml
@model CaffeineBookatableProject.Models.Jobrespons

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Jobrespons</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.user_id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Job_Position, "Job_Position", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Job_Position", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Job_Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Resume, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Resume, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Resume, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CaffeineBookatableProject/Views/Jobrespons/Index.cshtml
@model IEnumerable<CaffeineBookatableProject.Models.Jobrespons>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}



<!DOCTYPE html>
<html>
<head>
    <title>Your Table</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

    <div class="container">
        <h3>
            <center> Job Applications</center> 
        </h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Designation</th>
                    <th>Resume</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Email)</td>
                        <td>@Html.DisplayFor(modelItem => item.Phone)</td>
                        <td>@Html.DisplayFor(modelItem => item.Carrer.carrer_designation)</td>
                        <td>
                            <a href="@Url.Content(item.Resume)" class="btn btn-success">View</a> |
                            @Html.ActionLink("Details", "Details", new { id = item.user_id }, new { @class = "btn btn-info" }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.user_id }, new { @class = "btn btn-danger" })
                        </td>
                        <td>
                            
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</body>
</html>