CaffeineBookatableProject/Models/Outlet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaffeineBookatableProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Outlet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Outlet()
        {
            this.Dinetables = new HashSet<Dinetable>();
        }
    
        public int outlet_id { get; set; }
        public string outlet_name { get; set; }
        public string outlet_disc { get; set; }
        public string outlet_location { get; set; }
        public string outlet_pic { get; set; }
        public HttpPostedFileBase outle_pic { get; set; }
        public Nullable<int> branch_fid { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dinetable> Dinetables { get; set; }
    }
}

CaffeineBookatableProject/Controllers/OutletsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CaffeineBookatableProject.Models;

namespace CaffeineBookatableProject.Controllers
{
    public class OutletsController : Controller
    {
        private OnlineBookingEntities db = new OnlineBookingEntities();

        // GET: Outlets
        public ActionResult Index()
        {
            var outlets = db.Outlets.Include(o => o.Branch);https://localhost:44308/Models/Product.cs
            return View(outlets.ToList());
        }

        // GET: Outlets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Outlet outlet = db.Outlets.Find(id);
            if (outlet == null)
            {
                return HttpNotFound();
            }
            return View(outlet);
        }

        // GET: Outlets/Create
        public ActionResult Create()
        {
            ViewBag.branch_fid = new SelectList(db.Branches, "branch_id", "branch_name");
            return View();
        }

        // POST: Outlets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Outlet outlet)
        {
            
            if (ModelState.IsValid)
            {

                outlet.outle_pic.SaveAs(Server.MapPath("~/OutPic/" + outlet.outle_pic.FileName));
                //product.Prod_Pic = "~/ProPic/" + product.Pro_Pic.FileName;
                if (outlet.outle_pic.FileName != "")
                {
                    outlet.outlet_pic = "~/OutPic/" + outlet.outle_pic.FileName;
                    db.Outlets.Add(outlet);
                    db.SaveChanges();
                }
                else
                {
                    outlet.outlet_pic = null;
                }

                return RedirectToAction("Index");
            }

            ViewBag.branch_fid = new SelectList(db.Branches, "branch_id", "branch_name", outlet.branch_fid);
            return View(outlet);
        }

        // GET: Outlets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Outlet outlet = db.Outlets.Find(id);
            if (outlet == null)
            {
                return HttpNotFound();
            }
            ViewBag.branch_fid = new SelectList(db.Branches, "branch_id", "branch_name", outlet.branch_fid);
            return View(outlet);
        }

        // POST: Outlets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "outlet_id,outlet_name,outlet_disc,outlet_location,outlet_pic,branch_fid")] Outlet outlet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(outlet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.branch_fid = new SelectList(db.Branches, "branch_id", "branch_name", outlet.branch_fid);
            return View(outlet);
        }

        // GET: Outlets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Outlet outlet = db.Outlets.Find(id);
            if (outlet == null)
            {
                return HttpNotFound();
            }
            return View(outlet);
        }

        // POST: Outlets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Outlet outlet = db.Outlets.Find(id);
            db.Outlets.Remove(outlet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CaffeineBookatableProject/Views/Outlets/Create.cshtml
@model CaffeineBookatableProject.Models.Outlet

@{
    ViewBag.Title = "Create";
}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main ">
    <h2>Create</h2>

    @using (Html.BeginForm("Create","Outlets",FormMethod.Post ,new{ enctype = "multipart/form-data" }) )
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Outlet</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.outlet_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.outlet_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.outlet_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.outlet_disc, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.outlet_disc, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.outlet_disc, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.outlet_location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.outlet_location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.outlet_location, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.outlet_pic, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="outle_pic" required />
                    @*@Html.EditorFor(model => model.outlet_pic, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.outlet_pic, "", new { @class = "text-danger" })*@
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.branch_fid, "branch_fid", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("branch_fid", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.branch_fid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-outline-success" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

CaffeineBookatableProject/Views/Outlets/Delete.cshtml
@model CaffeineBookatableProject.Models.Outlet

@{
    ViewBag.Title = "Delete";
}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main ">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Outlet</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.outlet_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.outlet_name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.outlet_disc)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.outlet_disc)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.outlet_location)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.outlet_location)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.outlet_pic)
            </dt>

            <dd>
                <img src="@Url.Content(Model.outlet_pic)" width="50px" />
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Branch.branch_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Branch.branch_name)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
    </div>

CaffeineBookatableProject/Views/Outlets/Details.cshtml
@model CaffeineBookatableProject.Models.Outlet

@{
    ViewBag.Title = "Details";
}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main ">
    <h2>Details</h2>

    <div>
        <h4>Outlet</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.outlet_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.outlet_name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.outlet_disc)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.outlet_disc)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.outlet_location)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.outlet_location)
            </dd>

            <dt>
                <img src="@Url.Content(Model.outlet_pic)" width="50px" />
            </dt>

            <dd>
                @Html.DisplayFor(model => model.outlet_pic)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Branch.branch_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Branch.branch_name)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.outlet_id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
   </div>

CaffeineBookatableProject/Views/Outlets/Edit.cshtml
@model CaffeineBookatableProject.Models.Outlet

@{
    ViewBag.Title = "Edit";
}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main ">
    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Outlet</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.outlet_id)

            <div class="form-group">
                @Html.LabelFor(model => model.outlet_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.outlet_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.outlet_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.outlet_disc, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.outlet_disc, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.outlet_disc, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.outlet_location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.outlet_location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.outlet_location, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.outlet_pic, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.outlet_pic, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.outlet_pic, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.branch_fid, "branch_fid", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("branch_fid", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.branch_fid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
 </div>

CaffeineBookatableProject/Views/Outlets/Index.cshtml
@model IEnumerable<CaffeineBookatableProject.Models.Outlet>

@{
    ViewBag.Title = "Index";
}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <h2>Outlet List</h2>

    <p>
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-success" })
    </p>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        Outlet Name
                    </th>
                    <th>
                        Outlet Description
                    </th>
                    <th>
                        Outlet Location
                    </th>
                    <th>
                        Outlet Picture
                    </th>
                    <th>
                        Branch
                    </th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.outlet_name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.outlet_disc)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.outlet_location)
                        </td>
                        <td>
                            <img src="@Url.Content(item.outlet_pic)" width="50px" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Branch.branch_name)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.outlet_id }, new { @class = "btn btn-primary" })
                            <span class="btn-separator">|</span>
                            @Html.ActionLink("Details", "Details", new { id = item.outlet_id }, new { @class = "btn btn-info" })
                            <span class="btn-separator">|</span>
                            @Html.ActionLink("Delete", "Delete", new { id = item.outlet_id }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>